repos:
    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.2
      hooks:
        - id: seed-isort-config
    - repo: https://github.com/timothycrosley/isort
      rev: 18ad293fc9d1852776afe35015a932b68d26fb14
      hooks:
        - id: isort
          exclude: ^docs/

    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black
          exclude: ^docs/

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
        - id: flake8
          types:
            - python
          exclude: ^docs/

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'master'
      hooks:
      -   id: mypy
          files: dmelon/

